# Generated by Django 4.2.7 on 2024-01-17 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_notes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
